import org.mentalizr.backend.build.task.CopyStaticResourcesFromFrontendTask
import org.mentalizr.backend.build.task.ExpandInitHtmlTask

import java.nio.file.Files
import java.nio.file.Paths
import java.text.SimpleDateFormat

plugins {
    id 'war'
}

group = 'org.mentalizr'
version = '0.1-SNAPSHOT'

repositories {
    mavenCentral()
    maven { url = "https://raw.githubusercontent.com/arthurpicht/mvn-repo/main/releases"}
}

dependencies {
    providedCompile libs.jakarta.servlet.api

    implementation libs.m7r.commons
    implementation libs.m7r.backendProc
    implementation libs.m7r.persistenceMongo
    implementation libs.m7r.persistenceRdbms
    implementation libs.m7r.backendConfig
    implementation libs.m7r.serviceObjects
    implementation libs.m7r.contentManager

    implementation libs.ap.utils.core
    implementation libs.ap.utils.io
    implementation libs.ap.web.access.control

    implementation libs.jersey.server
    implementation libs.jersey.hk2
    implementation libs.jersey.container.servlet
    implementation libs.jersey.container.jdk.http
    implementation libs.jersey.media.jaxb
    implementation libs.jersey.media.json.binding

    implementation libs.jakarta.xml.bind.api

    implementation libs.qos.logback

    testImplementation libs.junit.jupiter
    testRuntimeOnly libs.junit.engine
}

test {
    useJUnitPlatform()
}

war() {
    archiveFileName = 'm7r.war'
    from('conf') {
        include 'logback.xml'
        into 'WEB-INF/classes'
    }
}

tasks.register('createBuildIdFile') {
    new File("src/main/resources/", "buildId.txt").text = """${new SimpleDateFormat("yyyyMMddHHmmss").format(new Date())}"""
}

tasks.register('expandInitHtml', ExpandInitHtmlTask)
tasks.register('copyStaticResourcesFromFrontend', CopyStaticResourcesFromFrontendTask)

tasks.register('copyBarnacleConf', Copy) {
    def userHome = System.getProperty("user.home")
    def configDir = Paths.get(userHome).resolve(".m7r-host/config").normalize()
    if (!Files.exists(configDir)) throw new GradleException(configDir.toAbsolutePath().toString() + ' not found.')

    def barnacleConf = configDir.resolve("common/barnacle.conf").toFile()
    if (!barnacleConf.exists()) throw new GradleException(barnacleConf.absolutePath + ' not found.')

    inputs.file(barnacleConf)
    outputs.file("$rootDir/src/main/resources/barnacle.conf")

    from file(barnacleConf)
    into "$rootDir/src/main/resources"
}

tasks.register('copyWebAppConf', Copy) {
    def userHome = System.getProperty("user.home")
    def configDir = Paths.get(userHome).resolve(".m7r-host/config").normalize()
    if (!Files.exists(configDir)) throw new GradleException(configDir.toAbsolutePath().toString() + " not found." as String)

    def logbackConf = configDir.resolve("common/logback.xml").toFile()
    if (!logbackConf.exists()) throw new GradleException(logbackConf.absolutePath + ' not found.')
    inputs.file(logbackConf)
    outputs.file("$rootDir/conf/logback.xml")
    from file(logbackConf)

    into "$rootDir/conf"
}

clean {
    delete "$rootDir/src/main/resources/barnacle.conf"
    delete "$rootDir/conf/logback.xml"
    delete fileTree("$rootDir/src/main/webapp/WEB-INF").include('*.html')
}

processResources {
    dependsOn copyBarnacleConf
}

war.dependsOn expandInitHtml
war.dependsOn copyStaticResourcesFromFrontend
war.dependsOn copyBarnacleConf
war.dependsOn copyWebAppConf
war.dependsOn createBuildIdFile

defaultTasks 'war'